// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4x4hG3F3aZNyJcY-xx8lvIfUyzvsqn8',
    appId: '1:747092674378:web:dff0d413f0888423b5e3b3',
    messagingSenderId: '747092674378',
    projectId: 'retailapp-8ea0c',
    authDomain: 'retailapp-8ea0c.firebaseapp.com',
    databaseURL: 'https://retailapp-8ea0c-default-rtdb.firebaseio.com',
    storageBucket: 'retailapp-8ea0c.appspot.com',
    measurementId: 'G-Z2JLQSYB0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSsJwzfa-JGC9QBZiaEoty5rgo7bETQ9o',
    appId: '1:747092674378:android:5bc56c9a642502d7b5e3b3',
    messagingSenderId: '747092674378',
    projectId: 'retailapp-8ea0c',
    databaseURL: 'https://retailapp-8ea0c-default-rtdb.firebaseio.com',
    storageBucket: 'retailapp-8ea0c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe4x4hG3F3aZNyJcY-xx8lvIfUyzvsqn8',
    appId: '1:747092674378:web:aee1e25c8b073970b5e3b3',
    messagingSenderId: '747092674378',
    projectId: 'retailapp-8ea0c',
    authDomain: 'retailapp-8ea0c.firebaseapp.com',
    databaseURL: 'https://retailapp-8ea0c-default-rtdb.firebaseio.com',
    storageBucket: 'retailapp-8ea0c.appspot.com',
    measurementId: 'G-B4J6Z0HF7T',
  );
}
